namespace Ucommerce.UI.Samples.Mvc.Models
{
    /// <summary>
    /// Class that is registered automatically in the Ucommerce DI container as an implementation of <see cref="IDiAutoModel"/> on application start.
    /// </summary>
    public class DiAutoModel : IDiAutoModel
    {
        public DependencyInjectionViewModel GetViewModel()
        {
            return new DependencyInjectionViewModel()
            {
                Message = "This message is generated by a widget with dependencies that are registered automatically in the Castle Windsor DI container on application start."
            };
        }
    }
}
