namespace Ucommerce.UI.Samples.Mvc.Models
{
    /// <summary>
    /// Class that is registered manually in the Ucommerce DI container as an implementation of <see cref="IDiManualModel"/> on container initialized event.
    /// </summary>
    public class DiManualModel : IDiManualModel
    {
        public DependencyInjectionViewModel GetViewModel()
        {
            return new DependencyInjectionViewModel()
            {
                Message = "This message is generated by a widget with dependencies registered manually in the Castle Windsor DI container on WindsorContainerInitialized event."
            };
        }
    }
}
